[package]
name = "reflection"
version = "0.1.0"
edition = "2021"

[dependencies]
reflection-proc = { path = "reflection-proc" }

[lib]
name = "reflection"

[[bin]]
name = "example"
path = "example/main.rs"
