[package]
name = "reflection-proc"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full", "extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0"

[lib]
name = "reflection_proc"
proc-macro = true
